### ISSUE TITLE
development issues list

### ISSUE THREAD

**Issue by Aniket6990** [7finney/eth-abi-interactive#1]
1. Getting error messages while opening the extension in `extension host`.
![image](https://user-images.githubusercontent.com/87822922/227220973-1112d04e-bb19-49f1-8d86-7df039a1a3bb.png)
This is due to the commands that are present in the `menus` section but not registered in the `commands` section of the `package.json` file.

2. Getting an error message if the `fileName_address.json` file is not present for the contract that the user wants to select from the `contracts` section of the treeview.

3. Getting an error message if the deployed address is not inserted in the `fileName_address.json` file while calling a function.

**Comment by Aniket6990** [comment]
4. Enter values of the parameter must be visible in the parameter tree of the ABI.
![image](https://user-images.githubusercontent.com/87822922/227409899-80ed6723-3f74-43b7-90a7-0e07a817ae11.png)

5. A watcher should be available to watch the new changes in compiled JSON file of the smart contract. it should automatically refresh the contract list in the `contracts` tree.

6. replace this icon with refresh button to manually refresh the contract list in `contracts` tree.
<img width="195" alt="image" src="https://user-images.githubusercontent.com/87822922/227410573-e27d286a-2977-4330-a72d-ad48cd74cdb8.png">

**Comment by Aniket6990** [comment]
Whenever a user enters deployed address value in the address field of the `fileName_deployed_address.json` file then the state should be changed to the deployed address value from undefined.
<img width="947" alt="image" src="https://user-images.githubusercontent.com/87822922/228281714-8ee2abf1-c14b-4e7e-a8b6-70cbb1bee61a.png">

**Comment by Aniket6990** [comment]
Whenever a user selects a contract from the contract tree then the three files `fileName_deployed_address.json`, fileName_functionInput.json` fileName_constructorInput.json` for the selected contract should automatically create.

**Comment by Aniket6990** [comment]
The contact list is not refreshing when the user is clicking on the refresh button of the contract tree.
![image](https://user-images.githubusercontent.com/87822922/228820587-cc0c55bc-64d1-4f43-beea-512498f439a8.png)

**Comment by Krish-bhardwaj** [comment]
getting this error pop up on start of the extension 
![image](https://user-images.githubusercontent.com/72294477/228832704-90696296-7071-437e-b1f2-35d5781a5e3c.png)
